[toolchain]

[features]
seeds = false
skip-lint = false

[programs.mainnet]
lottery = "6mcti5AtPeQ368eSpEuaoqqkPpiMAYbzbmKTDwGD47Uc"

[programs.devnet]
lottery = "6mcti5AtPeQ368eSpEuaoqqkPpiMAYbzbmKTDwGD47Uc"

[programs.localnet]
lottery = "6mcti5AtPeQ368eSpEuaoqqkPpiMAYbzbmKTDwGD47Uc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/odmin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
